version: '3.8'

services:
  app:
    image: openjdk:23
    container_name: java_app
    working_dir: /app
    volumes:
      - ./application.jar:/app/application.jar
    ports:
      - "8080:8080"
    command: ["java", "-jar", "application.jar"]
